#!/bin/sh

if [ "$#" -lt 1 ] ; then
  echo Usage: $0 '[rustdesk:id]'
  exit 1
fi

# removes the initial rustdek:
# (posix standard, should work in every shell)
id="${@#rustdesk:}"

# we don't do sanity check of the passed url
# we just pass it directly to rustdesk
# which will raise an error if the id is incorrect

/usr/bin/rustdesk --connect "${id}"
