#!/usr/bin/env python3
"""Apply build-time white-label settings to the RustDesk Flutter clients."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape


ROOT = Path(__file__).resolve().parents[1]


def fail(message: str) -> None:
    raise SystemExit(f"white-label: {message}")


def load_config(path: Path) -> dict[str, Any]:
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read {path}: {exc}")
    missing = [key for key in ("app_name", "bundle_id", "url_scheme") if not config.get(key)]
    if missing:
        fail(f"missing required settings: {', '.join(missing)}")
    if not re.fullmatch(r"[a-z][a-z0-9+.-]*", config["url_scheme"]):
        fail("url_scheme must be a lowercase URI scheme")
    if not re.fullmatch(r"[A-Za-z0-9.-]+", config["bundle_id"]):
        fail("bundle_id may only contain letters, numbers, dots and hyphens")
    for key in ("app_name", "company_name", "copyright"):
        value = config.get(key, "")
        if any(char in value for char in ('"', "\r", "\n")):
            fail(f"{key} may not contain quotes or newlines")
    return config


def replace_regex(path: str, pattern: str, replacement: str) -> None:
    file_path = ROOT / path
    text = file_path.read_text(encoding="utf-8")
    updated, count = re.subn(pattern, replacement, text, flags=re.MULTILINE)
    if count == 0:
        fail(f"expected pattern not found in {path}: {pattern!r}")
    file_path.write_text(updated, encoding="utf-8")


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def rust_pairs(value: Any, name: str) -> str:
    value = value or {}
    if not isinstance(value, dict) or not all(
        isinstance(key, str) and isinstance(item, str) for key, item in value.items()
    ):
        fail(f"{name} must be an object containing string values")
    return ",\n    ".join(
        f"({rust_string(key)}, {rust_string(item)})" for key, item in sorted(value.items())
    )


def rust_array(value: Any, name: str) -> str:
    pairs = rust_pairs(value, name)
    return f"&[\n    {pairs},\n]" if pairs else "&[]"


def write_generated_rust(config: dict[str, Any]) -> None:
    update = config.get("updates") or {}
    if not isinstance(update, dict):
        fail("updates must be an object")
    generated = f"""// Generated by tools/white_label.py. Do not edit by hand.
pub const APP_NAME: &str = {rust_string(config["app_name"])};
pub const UPDATE_CHECK_URL: &str = {rust_string(update.get("check_url", ""))};
pub const WINDOWS_DOWNLOAD_URL_TEMPLATE: &str = {rust_string(update.get("windows_download_url_template", ""))};
pub const DEFAULT_SETTINGS: &[(&str, &str)] = {rust_array(config.get("default_settings"), "default_settings")};
pub const OVERRIDE_SETTINGS: &[(&str, &str)] = {rust_array(config.get("override_settings"), "override_settings")};
"""
    (ROOT / "src/white_label_generated.rs").write_text(generated, encoding="utf-8")


def copy_icons(config: dict[str, Any], config_path: Path, generate_icons: bool) -> None:
    ui_logo = config.get("ui_logo")
    if ui_logo:
        ui_logo_path = (config_path.parent / ui_logo).resolve()
        if not ui_logo_path.is_file():
            fail(f"ui_logo does not exist: {ui_logo_path}")
        shutil.copyfile(ui_logo_path, ROOT / "flutter/assets/icon.svg")

    icon = config.get("icon")
    if not icon:
        return
    icon_path = (config_path.parent / icon).resolve()
    if not icon_path.is_file():
        fail(f"icon does not exist: {icon_path}")
    shutil.copyfile(icon_path, ROOT / "res/icon.png")

    mac_icon = config.get("mac_icon")
    mac_icon_path = (config_path.parent / mac_icon).resolve() if mac_icon else icon_path
    if not mac_icon_path.is_file():
        fail(f"mac_icon does not exist: {mac_icon_path}")
    shutil.copyfile(mac_icon_path, ROOT / "res/mac-icon.png")

    mac_icns = config.get("mac_icns")
    if mac_icns:
        mac_icns_path = (config_path.parent / mac_icns).resolve()
        if not mac_icns_path.is_file():
            fail(f"mac_icns does not exist: {mac_icns_path}")
        shutil.copyfile(mac_icns_path, ROOT / "flutter/macos/Runner/AppIcon.icns")

    if generate_icons:
        dart = shutil.which("dart")
        if not dart:
            fail("dart is required to generate platform icons")
        subprocess.run(
            [dart, "run", "flutter_launcher_icons"],
            cwd=ROOT / "flutter",
            check=True,
        )


def apply(config: dict[str, Any], config_path: Path, generate_icons: bool) -> None:
    app_name = config["app_name"]
    bundle_id = config["bundle_id"]
    scheme = config["url_scheme"]
    company = config.get("company_name", app_name)
    copyright_text = config.get("copyright", f"Copyright (c) {company}. All rights reserved.")

    write_generated_rust(config)
    copy_icons(config, config_path, generate_icons)

    replace_regex("flutter/android/app/build.gradle", r'applicationId "[^"]+"', f'applicationId "{bundle_id}"')
    replace_regex("flutter/android/app/src/main/res/values/strings.xml", r'<string name="app_name">[^<]*</string>', f'<string name="app_name">{escape(app_name)}</string>')
    replace_regex("flutter/android/app/src/main/AndroidManifest.xml", r'(android:icon="@mipmap/ic_launcher"\s+android:label=")[^"]+(")', rf'\g<1>@string/app_name\g<2>')
    replace_regex("flutter/android/app/src/main/AndroidManifest.xml", r'<data android:scheme="[^"]+" />', f'<data android:scheme="{scheme}" />')

    replace_regex("flutter/macos/Runner/Configs/AppInfo.xcconfig", r"^PRODUCT_NAME = .+$", f"PRODUCT_NAME = {app_name}")
    replace_regex("flutter/macos/Runner/Configs/AppInfo.xcconfig", r"^PRODUCT_BUNDLE_IDENTIFIER = .+$", f"PRODUCT_BUNDLE_IDENTIFIER = {bundle_id}")
    replace_regex("flutter/macos/Runner/Configs/AppInfo.xcconfig", r"^PRODUCT_COPYRIGHT = .+$", f"PRODUCT_COPYRIGHT = {copyright_text}")
    for plist in ("flutter/macos/Runner/Info.plist", "flutter/ios/Runner/Info.plist"):
        replace_regex(plist, r"(<key>CFBundleURLName</key>\s*<string>)[^<]*(</string>)", rf"\g<1>{bundle_id}\g<2>")
        replace_regex(plist, r"(<key>CFBundleURLSchemes</key>\s*<array>\s*<string>)[^<]*(</string>)", rf"\g<1>{scheme}\g<2>")
    replace_regex("flutter/ios/Runner/Info.plist", r"(<key>CFBundleDisplayName</key>\s*<string>)[^<]*(</string>)", rf"\g<1>{escape(app_name)}\g<2>")
    replace_regex("flutter/ios/Runner/Info.plist", r"(<key>CFBundleName</key>\s*<string>)[^<]*(</string>)", rf"\g<1>{escape(app_name)}\g<2>")
    replace_regex("flutter/ios/Runner.xcodeproj/project.pbxproj", r"PRODUCT_BUNDLE_IDENTIFIER = [^;]+;", f"PRODUCT_BUNDLE_IDENTIFIER = {bundle_id};")

    replace_regex("flutter/windows/runner/Runner.rc", r'VALUE "CompanyName", "[^"]*"', f'VALUE "CompanyName", "{company}"')
    replace_regex("flutter/windows/runner/Runner.rc", r'VALUE "FileDescription", "[^"]*"', f'VALUE "FileDescription", "{app_name} Remote Desktop"')
    replace_regex("flutter/windows/runner/Runner.rc", r'VALUE "LegalCopyright", "[^"]*"', f'VALUE "LegalCopyright", "{copyright_text}"')
    replace_regex("flutter/windows/runner/Runner.rc", r'VALUE "ProductName", "[^"]*"', f'VALUE "ProductName", "{app_name}"')
    replace_regex("flutter/linux/CMakeLists.txt", r'set\(APPLICATION_ID "[^"]+"\)', f'set(APPLICATION_ID "{bundle_id}")')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("config", type=Path, help="path to a white-label JSON file")
    parser.add_argument("--generate-icons", action="store_true", help="run flutter_launcher_icons after copying the configured icon")
    parser.add_argument("--check", action="store_true", help="validate the config without changing files")
    args = parser.parse_args()
    config_path = args.config.resolve()
    config = load_config(config_path)
    if args.check:
        print(f"white-label: {config_path} is valid")
        return
    apply(config, config_path, args.generate_icons)
    print(f"white-label: applied {config['app_name']!r}")


if __name__ == "__main__":
    main()
