// Generated by tools/white_label.py. Do not edit by hand.
pub const APP_NAME: &str = "";
pub const UPDATE_CHECK_URL: &str = "";
pub const WINDOWS_DOWNLOAD_URL_TEMPLATE: &str = "";
pub const DEFAULT_SETTINGS: &[(&str, &str)] = &[];
pub const OVERRIDE_SETTINGS: &[(&str, &str)] = &[];
