#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/kassatkadesk/kassatkadesk /usr/bin/kassatkadesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/kassatkadesk.service ]; then
			rm /etc/systemd/system/kassatkadesk.service /usr/lib/systemd/system/kassatkadesk.service /usr/lib/systemd/user/kassatkadesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/kassatkadesk/files/systemd/rustdesk.service /usr/lib/systemd/system/kassatkadesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload kassatkadesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/kassatkadesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/kassatkadesk.service
		fi
		systemctl daemon-reload
		systemctl enable kassatkadesk
		systemctl start kassatkadesk
	fi
fi
