#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/stardesk/stardesk /usr/bin/stardesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/stardesk.service ]; then
			rm /etc/systemd/system/stardesk.service /usr/lib/systemd/system/stardesk.service /usr/lib/systemd/user/stardesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/stardesk/files/systemd/stardesk.service /usr/lib/systemd/system/stardesk.service
		systemctl daemon-reload
		systemctl enable stardesk
		systemctl start stardesk
	fi
fi
