#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		
		if [ "systemd" == "${INITSYS}" ]; then
			rm /usr/bin/rustdesk

			systemctl stop rustdesk || true
			systemctl disable rustdesk || true
			rm /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'rustdesk +--server' | awk '{print $1}' | head -1)
			ubuntuVersion=$(grep -oP 'VERSION_ID="\K[\d]+' /etc/os-release | bc -l)
			waylandSupportVersion=21
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ] && [ "$ubuntuVersion" -ge "$waylandSupportVersion" ]
			then
				systemctl --machine=${serverUser}@.host --user stop rustdesk || true
			fi	
			rm /usr/lib/systemd/user/rustdesk.service >/dev/null 2>/dev/null || true
		fi
        ;;
esac

exit 0
