name: Flutter Nightly Build

on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: rustdesk/rustdesk/.github/workflows/flutter-build.yml@master
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
