name: Restore Tag

on:
  workflow_dispatch:

jobs:
  restore-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CheckoutCode }}

      - name: Fetch and Push Tag
        run: |
          git remote add upstream https://github.com/rustdesk/rustdesk.git
          git fetch upstream --tags
          git push origin 1.4.7
