name: Flutter OpenHarmony CI

on:
  push:
    branches: [feat/ohos-unified-core-flutter]
  workflow_dispatch:
    inputs:
      upload-artifact:
        description: Upload the native library and Flutter HAP
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  build-rustdesk-ohos-flutter:
    uses: ./.github/workflows/flutter-ohos.yml
    with:
      upload-artifact: ${{ github.event_name == 'workflow_dispatch' && inputs.upload-artifact }}
      publish-release: false
      upload-tag: nightly
      version: "1.4.9"
